"""
Email Dataset for Spam Detection
Bhai yeh tumhara diya hua data hai - kisi website se nahi liya!
"""

SPAM_EMAILS = [
    {"email": "Congratulations! You won $1,000,000! Click here to claim now!", "label": "spam"},
    {"email": "FREE iPhone 15! Limited offer! Act now!", "label": "spam"},
    {"email": "You have been selected for a lottery prize of $500,000", "label": "spam"},
    {"email": "Make money fast! Earn $5000 daily from home!", "label": "spam"},
    {"email": "URGENT: Your bank account will be closed today!", "label": "spam"},
    {"email": "Buy cheap medicines online without prescription!", "label": "spam"},
    {"email": "You are our lucky winner! Claim your gift card now!", "label": "spam"},
    {"email": "Hot singles near you want to chat now!", "label": "spam"},
    {"email": "Increase your income by 500% instantly!", "label": "spam"},
    {"email": "Your account has been compromised! Verify now!", "label": "spam"},
    {"email": "Get rich quick with this secret investment!", "label": "spam"},
    {"email": "FREE trial! Miracle weight loss pills!", "label": "spam"},
    {"email": "You won a brand new luxury car!", "label": "spam"},
    {"email": "Nigerian prince needs your help transferring $10M", "label": "spam"},
    {"email": "Double your bitcoin in 24 hours!", "label": "spam"},
    {"email": "Act fast! Exclusive deal expires today!", "label": "spam"},
    {"email": "Earn passive income with no work!", "label": "spam"},
    {"email": "Limited time offer! Buy now and save 90%", "label": "spam"},
    {"email": "Your PayPal account is suspended!", "label": "spam"},
    {"email": "Click here to secure your prize!", "label": "spam"},
    {"email": "Win cash instantly! No skills required!", "label": "spam"},
    {"email": "Secret method to make money revealed!", "label": "spam"},
    {"email": "Urgent action required to avoid penalty!", "label": "spam"},
    {"email": "Congratulations! Selected for exclusive rewards!", "label": "spam"},
    {"email": "Cheap luxury watches available now!", "label": "spam"},
    {"email": "Your ATM card will be blocked!", "label": "spam"},
    {"email": "Free vacation package waiting for you!", "label": "spam"},
    {"email": "Lowest price ever! Buy today!", "label": "spam"},
    {"email": "You have unclaimed funds!", "label": "spam"},
    {"email": "Earn money while you sleep!", "label": "spam"},
    {"email": "Bitcoin investment with guaranteed profit!", "label": "spam"},
    {"email": "Special discount only for you!", "label": "spam"},
    {"email": "Verify your account to avoid suspension!", "label": "spam"},
    {"email": "Win big prizes with one click!", "label": "spam"},
    {"email": "Cheap loans approved instantly!", "label": "spam"},
    {"email": "Free coupons worth $500!", "label": "spam"},
    {"email": "Your credit score is at risk!", "label": "spam"},
    {"email": "Act now! Last chance to claim!", "label": "spam"},
    {"email": "Make $10,000 this week!", "label": "spam"},
    {"email": "Unlock hidden income secrets!", "label": "spam"},
    {"email": "Congratulations! Cash reward waiting!", "label": "spam"},
    {"email": "Exclusive VIP investment opportunity!", "label": "spam"},
    {"email": "Win free gadgets today!", "label": "spam"},
    {"email": "Urgent payment confirmation needed!", "label": "spam"},
    {"email": "Cheap airline tickets available now!", "label": "spam"},
    {"email": "You have won an iPad!", "label": "spam"},
    {"email": "Earn from mobile with no investment!", "label": "spam"},
    {"email": "Free Netflix subscription!", "label": "spam"},
    {"email": "Claim your free bonus now!", "label": "spam"},
    {"email": "Instant loan approval guaranteed!", "label": "spam"},
    {"email": "Your account will be deactivated!", "label": "spam"},
    {"email": "Win lottery without ticket!", "label": "spam"},
    {"email": "Secret crypto opportunity revealed!", "label": "spam"},
    {"email": "Lowest insurance rates available!", "label": "spam"},
    {"email": "Cash prize waiting for confirmation!", "label": "spam"},
    {"email": "Free shopping vouchers!", "label": "spam"},
    {"email": "Earn extra income today!", "label": "spam"},
    {"email": "Immediate response required!", "label": "spam"},
    {"email": "Limited offer on premium products!", "label": "spam"},
    {"email": "You are selected for mega rewards!", "label": "spam"},
    {"email": "Guaranteed profits or money back!", "label": "spam"},
    {"email": "Urgent security alert!", "label": "spam"},
    {"email": "Free trial offer expires soon!", "label": "spam"},
    {"email": "Win a brand new smartphone!", "label": "spam"},
    {"email": "High return investment plan!", "label": "spam"},
    {"email": "Claim your lucky draw prize!", "label": "spam"},
    {"email": "No-risk income opportunity!", "label": "spam"},
    {"email": "Fast cash loans approved!", "label": "spam"},
    {"email": "Act now to avoid account closure!", "label": "spam"},
    {"email": "You won big! Claim immediately!", "label": "spam"},
]

NOT_SPAM_EMAILS = [
    {"email": "Hi John, can we meet tomorrow at 3 PM?", "label": "not_spam"},
    {"email": "Please find the attached project report.", "label": "not_spam"},
    {"email": "Reminder: Team lunch on Friday.", "label": "not_spam"},
    {"email": "Your order #12345 has been shipped.", "label": "not_spam"},
    {"email": "Your monthly bank statement is available.", "label": "not_spam"},
    {"email": "Meeting notes from today are attached.", "label": "not_spam"},
    {"email": "Happy birthday! Have a great day.", "label": "not_spam"},
    {"email": "Project submission deadline is Monday.", "label": "not_spam"},
    {"email": "Please review the attached document.", "label": "not_spam"},
    {"email": "Your appointment is confirmed.", "label": "not_spam"},
    {"email": "Hi Mom, I will visit this weekend.", "label": "not_spam"},
    {"email": "Meeting rescheduled to Wednesday.", "label": "not_spam"},
    {"email": "Your password has been changed.", "label": "not_spam"},
    {"email": "Please complete the survey by Friday.", "label": "not_spam"},
    {"email": "Thank you for attending the conference.", "label": "not_spam"},
    {"email": "Your ticket has been booked successfully.", "label": "not_spam"},
    {"email": "Invoice for last month is attached.", "label": "not_spam"},
    {"email": "Reminder: Doctor appointment tomorrow.", "label": "not_spam"},
    {"email": "Can you review my code changes?", "label": "not_spam"},
    {"email": "The class will start at 10 AM.", "label": "not_spam"},
    {"email": "Please update the document as discussed.", "label": "not_spam"},
    {"email": "Your subscription has been renewed.", "label": "not_spam"},
    {"email": "The meeting agenda is attached.", "label": "not_spam"},
    {"email": "Thanks for your quick response.", "label": "not_spam"},
    {"email": "Your payment was successful.", "label": "not_spam"},
    {"email": "Here is the feedback you requested.", "label": "not_spam"},
    {"email": "Let me know your availability.", "label": "not_spam"},
    {"email": "Reminder: Assignment due tomorrow.", "label": "not_spam"},
    {"email": "The server maintenance is scheduled.", "label": "not_spam"},
    {"email": "Your account settings were updated.", "label": "not_spam"},
    {"email": "Lunch meeting confirmed.", "label": "not_spam"},
    {"email": "Your refund has been processed.", "label": "not_spam"},
    {"email": "Please find the updated file attached.", "label": "not_spam"},
    {"email": "Welcome to the team!", "label": "not_spam"},
    {"email": "Your exam results are published.", "label": "not_spam"},
    {"email": "Reminder: Weekly standup meeting.", "label": "not_spam"},
    {"email": "Your delivery will arrive today.", "label": "not_spam"},
    {"email": "Thanks for submitting the form.", "label": "not_spam"},
    {"email": "Please confirm your attendance.", "label": "not_spam"},
    {"email": "Your profile has been updated.", "label": "not_spam"},
    {"email": "Can we postpone the meeting?", "label": "not_spam"},
    {"email": "Your course enrollment is confirmed.", "label": "not_spam"},
    {"email": "The report looks good.", "label": "not_spam"},
    {"email": "Please check the shared folder.", "label": "not_spam"},
    {"email": "Thanks for the update.", "label": "not_spam"},
    {"email": "Your support ticket is resolved.", "label": "not_spam"},
    {"email": "Happy anniversary!", "label": "not_spam"},
    {"email": "Please see comments in the document.", "label": "not_spam"},
    {"email": "Your registration is complete.", "label": "not_spam"},
    {"email": "Let's catch up tomorrow.", "label": "not_spam"},
    {"email": "Team outing planned next week.", "label": "not_spam"},
    {"email": "Your leave request is approved.", "label": "not_spam"},
    {"email": "Please share the final version.", "label": "not_spam"},
    {"email": "Meeting minutes are attached.", "label": "not_spam"},
    {"email": "Your password reset was successful.", "label": "not_spam"},
    {"email": "Welcome to the platform.", "label": "not_spam"},
    {"email": "Thanks for your feedback.", "label": "not_spam"},
    {"email": "Your order has been delivered.", "label": "not_spam"},
    {"email": "Reminder: Training session tomorrow.", "label": "not_spam"},
    {"email": "Looking forward to our meeting.", "label": "not_spam"},
]

def get_all_data():
    """Combine spam and not_spam emails"""
    return SPAM_EMAILS + NOT_SPAM_EMAILS

def get_spam_data():
    """Get only spam emails"""
    return SPAM_EMAILS

def get_not_spam_data():
    """Get only not_spam emails"""
    return NOT_SPAM_EMAILS